### ISSUE TITLE
Support for cuda nvcc

### ISSUE THREAD

**Issue by Char-Aznable** [boostorg/test#220]
I have been using Boost.Test to test some my GPU  code. The usage is do some computation on the GPU, sync the result back to host and compare it with the result computed on the host. Until boost 1.68 this works perfectly. But in boost 1.69, I'm no longer able to compile Boost.Test with the CUDA compiler nvcc. Consider this:
```
#define BOOST_TEST_MODULE example
#include <boost/test/included/unit_test.hpp>

BOOST_AUTO_TEST_CASE( free_test_function )
{
BOOST_TEST( true );
}

```
Compiling this with "nvcc -x cu test.cpp -o test -std=c++14 -I$BOOST_ROOT/include" gives error:
```
test.cpp(7): error: identifier "BOOST_TEST_TOOL_UNIV" is undefined

test.cpp(7): error: identifier "BOOST_TEST_TOOL_UNIV_EX" is undefined

test.cpp(7): error: identifier "CHECK" is undefined

test.cpp(7): error: identifier "BOOST_TEST_INVOKE_IF_N_ARGS" is undefined

4 errors detected in the compilation of "/tmp/64641903.1.login.q/tmpxft_0002a275_00000000-8_test.cpp1.ii"
```
where "$BOOST_ROOT" is where boost is installed. This example compiles and runs fine with gcc and clang. 

If I change line 83 of `$BOOST_ROOT/include/boost/preprocessor/config/config.hpp` from 
```
if defined __GCCXML__ || defined __CUDACC__ || defined __PATHSCALE__ || defined __DMC__ || defined __CODEGEARC__ || defined __BORLANDC__ || defined __MWERKS__ || ( defined __SUNPRO_CC && __SUNPRO_CC < 0x5120 ) || defined __HP_aCC && !defined __EDG__ || defined __MRC__ || defined __SC__ || (defined(__PGI) && !defined(__EDG__))
```
to 
```
if defined __GCCXML__ || defined __PATHSCALE__ || defined __DMC__ || defined __CODEGEARC__ || defined __BORLANDC__ || defined __MWERKS__ || ( defined __SUNPRO_CC && __SUNPRO_CC < 0x5120 ) || defined __HP_aCC && !defined __EDG__ || defined __MRC__ || defined __SC__ || (defined(__PGI) && !defined(__EDG__))
```
then the program works fine. Can I know the reason why nvcc is/was not supported?

**Comment by masterleinad** [comment]
I see the same issue with `pgc++ 18.10-1` in `boost-1.67.0`.

**Comment by raffienficiaud** [comment]
I believe for the CUDA case this is solved by https://github.com/boostorg/preprocessor/commit/c436de6142477dd2c432e0836004c2503ef3b0f1 and that should be in for Boost 1.72.

Would it be possible to give a try @Char-Aznable ?

@masterleinad I do not know about `pgc++` support in Boost. I can raise create a ticket on boost.preprocessor. In the meantime, would you please dump all the defines of your compiler? (like https://stackoverflow.com/a/2224357/1617295)

**Comment by aprokop** [comment]
@raffienficiaud in arborx/ArborX#168 we also encountered this issue. I tried all boost 1.68-1.71, and only 1.68 works. The patch that you linked to did not fix the issue.

**Comment by raffienficiaud** [comment]
Thanks for the update, I will have a look

**Comment by raffienficiaud** [comment]
Hi,

I created a branch `topic/GH-220-support-nvcc` with a blind fix on this topic. Would it be possible for anyone to test that branch?

Thanks!

**Comment by aprokop** [comment]
@raffienficiaud It's a bit hard for me to test this in its current form (I use spack to build boost packages). It is possible to instead install something like 1.71.0, and then patch the installation instead?

**Comment by Char-Aznable** [comment]
@raffienficiaud I manually applied the changes in branch `topic/GH-220-support-nvcc` to my pre-installed 1.71.0 and they work for me.

**Comment by raffienficiaud** [comment]
@Char-Aznable thanks for the feedback, @aprokop maybe this approach works for you as well?

**Comment by aprokop** [comment]
I'll try.

**Comment by aprokop** [comment]
I patched 1.71.0 install. Nothing changed, and I still observe the same errors. The patch I applied was taken to be a single commit from that branch:
```diff
diff --git a/include/boost/test/detail/config.hpp b/include/boost/test/detail/config.hpp                                                                                                                         
index 5130def674..df69b2d158 100644                                                                                                                                                                              
--- a/include/boost/test/detail/config.hpp                                                                                                                                                                       
+++ b/include/boost/test/detail/config.hpp                                                                                                                                                                       
@@ -139,6 +139,10 @@ class type_info;                                                                                                                                                                            
 #define BOOST_PP_VARIADICS 1                                                                                                                                                                                    
 #endif                                                                                                                                                                                                          
                                                                                                                                                                                                                 
+#if defined(__NVCC__)                                                                                                                                                                                           
+#define BOOST_PP_VARIADICS 1                                                                                                                                                                                    
+#endif                                                                                                                                                                                                          
+                                                                                                                                                                                                                
 #endif /* ifndef BOOST_PP_VARIADICS */                                                                                                                                                                          
                                                                                                                                                                                                                 
 //____________________________________________________________________________//                                                                                                                                
diff --git a/include/boost/test/unit_test_suite.hpp b/include/boost/test/unit_test_suite.hpp                                                                                                                     
index be862ef217..f74a4c47a5 100644                                                                                                                                                                              
--- a/include/boost/test/unit_test_suite.hpp                                                                                                                                                                     
+++ b/include/boost/test/unit_test_suite.hpp                                                                                                                                                                     
@@ -13,6 +13,7 @@                                                                                                                                                                                                
 #define BOOST_TEST_UNIT_TEST_SUITE_HPP_071894GER                                                                                                                                                                
                                                                                                                                                                                                                 
 // Boost.Test                                                                                                                                                                                                   
+#include <boost/test/detail/config.hpp>                                                                                                                                                                         
 #include <boost/test/framework.hpp>                                                                                                                                                                             
 #include <boost/test/tree/auto_registration.hpp>                                                                                                                                                                
 #include <boost/test/tree/test_case_template.hpp>   
```
and I checked the resulting files that it indeed applied.

**Comment by raffienficiaud** [comment]
> I also checked that we indeed enter #if defined(__NVCC__) clause through putting #error there.

so we *do* enter this part, correct? OTOH you are saying that you use GCC 7.4, I am a bit confused :)

**Comment by aprokop** [comment]
> so we _do_ enter this part, correct?
yes

> OTOH you are saying that you use GCC 7.4, I am a bit confused :)
7.4 is host compiler. Our package uses Kokkos, and its `nvcc_wrapper` tool which chooses the compiler depending on whether the file is being compiled for host or device. This should not matter, the errors are definitely coming from nvcc, based on their format (parenthesis, like `../test/tstHeapOperations.cpp(183): error`.

**Comment by Char-Aznable** [comment]
@aprokop Are you using header-only Boost.Test, the dynamic or static lib linked one?

**Comment by aprokop** [comment]
@Char-Aznable We do dynamic linking
```
target_compile_definitions(ArborX_LinearBVH.exe PRIVATE BOOST_TEST_DYN_LINK)
```

**Comment by raffienficiaud** [comment]
It would be helpful if you can provide me with the command line that is emitted by the compiler. Since you are using CMake, you can maybe use the make generator and use `VERBOSE=1`, and provide me with the command line the build system emits on the file that has the compilation issue.

I also assume that you have the exact same error as the one reported in the initial issue definition. If this is not the case, please provide me with the exact error as well.

Thanks!

**Comment by aprokop** [comment]
```
ccache /home/xap/local/opt/kokkos/bin/nvcc_wrapper  -DBOOST_ALL_NO_LIB -DBOOST_TEST_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -I../src -I../src/details -Iinclude -isystem /home/xap/local/opt/kokkos/include
 -isystem /home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-7.4.0/openmpi-3.1.4-oetr45yq7vnbcqhiiaalfkpoftuujlzn/include -isystem /home/xap/local/opt/spack/opt/spack/linux-ubuntu18.04-broadwe
ll/gcc-7.4.0/boost-1.71.0-tfmutpkhlyvlinpsbedzdrtmp7aapbrd/include -lineinfo -DKOKKOS_ENABLE_PROFILING -O2 -g -DNDEBUG   --std=c++14 -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -expt-extended-la
mbda -arch=sm_61 -Xcompiler -fopenmp -fdiagnostics-color -MD -MT test/CMakeFiles/ArborX_DetailsTreeTraversal.exe.dir/tstDetailsTreeTraversal.cpp.o -MF test/CMakeFiles/ArborX_DetailsTreeTraversal.exe.dir/tstDet
ailsTreeTraversal.cpp.o.d -o test/CMakeFiles/ArborX_DetailsTreeTraversal.exe.dir/tstDetailsTreeTraversal.cpp.o -c ../test/tstDetailsTreeTraversal.cpp
../test/tstDetailsTreeTraversal.cpp(36): error: identifier "BOOST_TEST_TOOL_UNIV" is undefined

../test/tstDetailsTreeTraversal.cpp(36): error: identifier "BOOST_TEST_TOOL_UNIV_EX" is undefined

../test/tstDetailsTreeTraversal.cpp(36): error: identifier "CHECK" is undefined
```

**Comment by Char-Aznable** [comment]
@aprokop The OP is a header-only use case so yours could be a different issue. I also tried using kokkos' nvcc_wrapper with the proposed patch and it worked fine. Along the same lines,  I am not sure how the patch here would interact with the installed dynamic libs so header patch might not work for you. I also assume you have clean the ccache for other potential confounding factors? Do you have a minimal reproducing case?

**Comment by Char-Aznable** [comment]
@raffienficiaud For the sake of time, can we conclude your proposed patch fix the issue? Maybe @aprokop can open another issue with example code for your case? I desperately need this because I can't afford patching up all the machines manually.

**Comment by aprokop** [comment]
I have no objections. I don't have a reproducer right now, and this is not a priority for me.

**Comment by raffienficiaud** [comment]
Fixed in master

**Comment by correaa** [comment]
Not sure if this is the conclusion of this thread but adding 
```c++
#if defined(__NVCC__)
#define BOOST_PP_VARIADICS 1
#endif
```
before incluing `boost/test/unit_test.hpp` seems to solve the problem, in Boost. 1.71 at least.

**Comment by raffienficiaud** [comment]
This is fixed in 1.73, would you please be able to check if that fix works for you @correaa ? If not please open a new ticket.
